ALTER TABLE supplier_company CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier_company_staff MODIFY sjs_suggest VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '设计师理念';
ALTER TABLE supplier_company_staff MODIFY gz_suggest VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '设计师介绍';
ALTER TABLE supplier_domain CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier_expire CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier_forman CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier_level CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier_pay CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier_proxy CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier MODIFY jkb_flag VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '家可保状态，1支持家可保，0不支持';
ALTER TABLE supplier MODIFY legal_person VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '法人';
ALTER TABLE supplier MODIFY business_code VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '从业资历';
ALTER TABLE supplier MODIFY bind_mobile VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '绑定手机';
ALTER TABLE supplier MODIFY cause VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier MODIFY sp_code VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '商家编码';
ALTER TABLE supplier MODIFY abbreviation VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '简称';
ALTER TABLE supplier MODIFY primary_business VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '主营业务';
ALTER TABLE supplier MODIFY pointx VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier MODIFY pointy VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE supplier MODIFY id_card VARCHAR(18) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '身份证号';